name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USER }}
          key: ${{ secrets.CPANEL_SSH_KEY }}
          port: ${{ secrets.CPANEL_PORT }}
          script_stop: true
          script: |
            cd /home/proyec19/tareas_app
            git fetch origin main
            git reset --hard origin/main
            bash scripts/deploy.sh